name: Remove Needs Label

runs:
  using: 'composite'
  steps:
    - name: 'Removes needs labels on issue close'
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: |
          needs PR
          needs spike
          needs community feedback
          needs proposal