name: 'Code Review Chat'
description: 'Notify in chat about build results.'
author: 'Jackson Kearl'
inputs:
  token:
    description: GitHub token.
    default: ${{ github.token }}
    required: true
  slack_token:
    description: Slack token.
    required: true
  storage_connection_string:
    description: Storage connection string.
    required: false
  notification_channel:
    description: 'Which channel to send notifications to. Defaults to none.'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
